apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-15-133
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-15-133 
  name: dotnet-15-133
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-15-133 
